name: Build Vite Frontend
run-name: ${{ github.actor }} is build vite frontend
on: [push]
jobs:
  build and deploy website:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build website
        run: pnpm run build:vite-frontend

      - name: Deploy website to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/vite-frontend/dist
